[package]
name = "chapter-2"
version = "0.1.0"
edition = "2021"
authors = ["hnidoaht-101 <larktoshad0wknight.101@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
